config/routes.rb
Ryno::Engine.routes.draw do
  resources :blocks do
    member do
      get :makecolumns
    end
  end
  resources :pages do
    member do
      get :publish
    end
  end
  resources :publishedpages
  root to: 'pages#index'
end

app/models/ryno/application_record.rb
module Ryno
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/ryno/block.rb
module Ryno
  class Block < ApplicationRecord
    belongs_to :page, optional: true
    belongs_to :block, optional: true
    has_rich_text :content
    has_many :blocks

    def columns?
      self.block_type == "columns"
    end

    def before_element
      self.page.blank? ? "block_#{self.block_id}_blockform" : "page_#{self.page_id}_blockform"
    end

    def parent_element
      self.page.blank? ? "block_#{self.block_id}_blocks" : "page_#{self.page_id}_blocks"
    end

  end
end

app/models/ryno/ip.rb
module Ryno
  class Ip < ApplicationRecord
    def expired?
      self.expires_at < Time.now
    end
  end
end

app/models/ryno/page.rb
module Ryno
  class Page < ApplicationRecord
    has_many :blocks
    has_one :publishedpage
    validates :url, presence: true
    validates :title, presence: true
    attr_accessor :rendered_content

    def get_title
      self.title.blank? ? "(untitled)" : self.title
    end
    def publish!
      create_publishedpage! if self.publishedpage.nil?
      self.publishedpage.update(url: self.url, content: self.rendered_content, page_id: self.id, title: self.get_title, seo_title: self.seo_title)
      Rails.application.reload_routes!
    end
    def create_publishedpage!
      Publishedpage.create(url: self.url, content: self.rendered_content, page_id: self.id, title: self.get_title, seo_title: self.seo_title)
      self.reload
    end
    def render_content(request)
      @no_edit_button = true
      self.rendered_content = ApplicationController.new.render_to_string(partial: 'ryno/pages/show', locals: { page: self, request: request, no_edit_button: @no_edit_button })
      #PagesController.show
      #self.blocks.pluck(:content).join('')
    end

  end
end

app/models/ryno/publishedpage.rb
module Ryno
  class Publishedpage < ApplicationRecord
    belongs_to :page
    def self.pages
      Publishedpage.pluck(:url,:id).map{|k,y|[k,y]}.inject(Hash.new{ |h,k| h[k]=[] }){ |h,(k,v)| h[k] = v; h }
    end

  end
end

app/controllers/ryno/application_controller.rb
module Ryno
  class ApplicationController < ::ApplicationController
    def must_be_admin
      begin
        render plain: 'Not available.' unless is_admin?
      rescue
        render plain: 'Not available.'
      end
    end
    def must_be_editor
      begin
        render plain: 'Not available.' unless is_editor?
      rescue
        render plain: 'Not available.'
      end
    end
  end
end

app/controllers/ryno/blocks_controller.rb
require_dependency "ryno/application_controller"

module Ryno
  class BlocksController < ApplicationController
    before_action :must_be_editor
    before_action :set_block, only: [:show,:update,:destroy,:makecolumns]

    # GET /blocks
    def index
      @blocks = Block.all
    end

    # GET /blocks/1
    def show
      @page = @block.page
      respond_to do |format|
        format.html { }
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(@block, partial: 'show', locals: {block: @block})
        }
      end
    end

    def new
      if params[:page_id]
        new_page
      elsif params[:block_id]
        new_block
      end
    end

    def new_page
      @page = Page.find(params[:page_id])
      @block = @page.blocks.create
      if params[:col] == 'left'
        @block.update(block_type: 'columns', css_classes: 'row')
        @block.blocks.create(css_classes: 'col-3')
        @block.blocks.create(css_classes: 'col-9')
      elsif params[:col] == 'right'
        @block.update(block_type: 'columns', css_classes: 'row')
        @block.blocks.create(css_classes: 'col-9')
        @block.blocks.create(css_classes: 'col-3')
      elsif params[:col] == 'mid'
        @block.update(block_type: 'columns', css_classes: 'row')
        @block.blocks.create(css_classes: 'col-6')
        @block.blocks.create(css_classes: 'col-6')
      end
      respond_to do |format|
        format.html { redirect_to @block }
        format.turbo_stream {
          render turbo_stream: turbo_stream.append("page_#{@page.id}_blockform", partial: 'show', locals: {block: @block})
        }
        format.js {}
      end
    end

    def new_block
      @parentblock = Block.find(params[:block_id])
      @block = @parentblock.blocks.create
      respond_to do |format|
        format.html { redirect_to @block }
        format.turbo_stream {
          render turbo_stream: turbo_stream.append("block_#{@parentblock.id}_blockform", partial: 'show', locals: {block: @block})
        }
        format.js {}
      end
    end

    def makecolumns
      if @block.blocks.size < 3
        @block.update(block_type: 'columns', css_classes: 'row')
        @block.blocks.create(css_classes: 'col-3')
        @block.blocks.create(css_classes: 'col-9')
        redirect_to @block
      else
        redirect_to @block
      end
    end

    def update
      if @block.update(block_params)
        redirect_to @block
      else
        render :edit
      end
    end

    def destroy
      @page = @block.page
      @block.destroy
      respond_to do |format|
        format.html { redirect_to page_url(@page), notice: 'Block Removed' }
        format.json { head :no_content }
        #format.turbo_stream { render turbo_stream: turbo_stream.prepend('posts', partial: 'post') }
        format.turbo_stream { render turbo_stream: turbo_stream.remove("block_#{@block.id}") }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_block
        @block = Block.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def block_params
        params.require(:block).permit(:page_id, :block_id, :blocks_order, :block_type, :css_classes, :dont_contain, :content)
      end
  end
end

app/controllers/ryno/pages_controller.rb
require_dependency "ryno/application_controller"

module Ryno
  class PagesController < ApplicationController
    before_action :must_be_editor
    before_action :set_page, only: [:show, :publish, :edit, :update, :destroy]

    def index
      @pages = Page.all
    end

    def show
      render :show
    end

    def new
      @page = Page.new
    end

    def edit
    end

    def publish
      @page.render_content(request)
      @page.publish!
      redirect_to @page
    end

    def create
      @page = Page.create(page_params)
      redirect_to @page
    end

    # PATCH/PUT /pages/1
    def update
      if @page.update(page_params)
        if (params[:publish])
          @page.render_content(request)
          @page.publish!
        end
        redirect_to edit_page_path(@page)
      else
        render :edit
      end

    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_page
        @page = Page.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def page_params
        params.require(:page).permit(:blocks_order, :url, :title, :seo_title, :description, :redirect_to, :css_classes)
      end
  end
end

app/controllers/ryno/publishedpages_controller.rb
require_dependency "ryno/application_controller"

module Ryno
  class PublishedpagesController < ApplicationController
    before_action :set_publishedpage, only: [:show]

    def show
      @html_title = @publishedpage.seo_title
      @page_title = @html_title
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_publishedpage
        @publishedpage = Publishedpage.find_by(url: params[:id])
      end
  end
end

app/helpers/ryno/application_helper.rb
module Ryno
  module ApplicationHelper
  end
end

app/views/layouts/rhino/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Page Editor</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <style>.row { width:100%;display: flex;} .cx { width: 50%; }</style>
  <%#= stylesheet_link_tag    "rhino/application", media: "all" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>

  <main role="main" class="container">
    <%= yield %>
  </main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/rhino/xapplication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Page Editor</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <style>.row { width:100%;display: flex;} .cx { width: 50%; }</style>
  <%#= stylesheet_link_tag    "ryno/application", media: "all" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>

  <main role="main" class="container">
    <%= yield %>
  </main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

app/views/ryno/blocks/_block.html.erb
<div class="block block_<%= @block.id %> <%= @block.css_classes.blank? ? 'mt-2 mb-2 pt-4 pb-4' : @block.css_classes %>">
  <%= @block.content %>
  <% for @block in @block.blocks %>
    <%= render @block %>
  <% end %>
</div>

app/views/ryno/blocks/_edit.html.erb
<div class="block block_<%= block.id %> m-4 p-4 card">
  <%= render partial: 'ryno/blocks/form', block: block %>
</div>

app/views/ryno/blocks/_form.html.erb
<% block = @block %>
<%= form_with(model: block, method: :patch, local: false) do |form| %>
  <% if block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(block.errors.count, "error") %> prohibited this challenge from being saved:</h2>
      <ul>
        <% block.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="advanced" style="display:none;">
    <div class="form-group">
      <%= form.label :css_classes %>
      <%= form.text_field :css_classes, class: 'form-control' %>
    </div>
  </div>

  <% b = "$('.block_#{block.id}_types,.block_#{block.id}_content,.block_#{block.id}_opts').toggle();return false;" %>
  <div class="form-group">
    <div class="block-opts block_<%= @block.id %>_opts text-right <%= 'position-absolute xt-50' if block.columns? %>">
      <div class="<%= 'position-absolute' unless block.columns? %> p-3" style="right:0;">
        <a href="#" class="btn btn-secondary mr-1" onclick="<%= b %>">&#x2699;</a>
        <a href="<%= block_path(block.id) %>" class="btn btn-light mr-1"
           data-turbo-frame="block_<%= block.id %>" data-turbo-method="delete">&times;</a>
      </div>
    </div>
    <div class="block_types block_<%= block.id %>_types <%= 'position-absolute xt-50' if block.columns? %>">
      <a href="#" class="btn btn-primary">Paragraph</a>
      <a href="#" class="btn btn-primary">Image</a>
      <%= link_to "Columns", makecolumns_block_path(block), class: 'btn btn-primary' %>
<!--      <a href="" class="btn btn-primary">Columns</a>-->
      <a href="#" class="btn btn-primary">CSS</a>
      <a href="#" class="btn btn-primary" onclick="<%= b %>">Cancel</a>
    </div>
    <div class="block_content block_<%= block.id %>_content">
      <%= form.rich_text_area :content unless (block.content.blank? && (block.block_type=="columns")) %>
    </div>
  </div>

  <div class="actions">
    <%#= form.submit %>
<!--    <button type="submit" class="btn btn-primary" action="submit" name="save">Save</button>-->
  </div>
<% end %>

app/views/ryno/blocks/_index.html.erb
<%= turbo_frame_tag "page_#{@page.id}_blockform" do %>
  <% for @block in @page.blocks %>
    <%= render partial: "ryno/blocks/show", block: @block %>
  <% end %>
  <%= render partial: 'ryno/blocks/new' %>
<% end %>

app/views/ryno/blocks/_new.html.erb
<%= turbo_frame_tag "page_#{@page.id}_blockform" do %>
  <div class="text-center addblockbuttons">
    <%= link_to "<img src='https://i.ani.me/0332/2951/col-0.png' alt='icon'>".html_safe, new_block_path(page_id: @page.id), class: 'm-2', data: { remote: true } %>
    <%= link_to "<img src='https://i.ani.me/0332/2945/c-left.png' alt='icon'>".html_safe, new_block_path(page_id: @page.id, col: :left), class: 'm-2', data: { remote: true } %>
    <%= link_to "<img src='https://i.ani.me/0332/2946/c-mid.png' alt='icon'>".html_safe, new_block_path(page_id: @page.id, col: :mid), class: 'm-2', data: { remote: true } %>
    <%= link_to "<img src='https://i.ani.me/0332/2950/col-right.png' alt='icon'>".html_safe, new_block_path(page_id: @page.id, col: :right), class: 'm-2', data: { remote: true } %>
    <%#= link_to "Add Block", new_block_path(page_id: @page.id), class: 'btn btn-primary m-2', data: { remote: true } %>
  </div>
<% end %>

app/views/ryno/blocks/_show.html.erb
<%= turbo_frame_tag @block, class: "#{@block.css_classes} p-4 position-relative block block_#{@block.id}" do %>
  <%= render partial: 'ryno/blocks/form', block: @block %>
  <% for @block in @block.blocks %>
    <%= render partial: 'ryno/blocks/show', block: @block %>
  <% end %>
<% end %>

app/views/ryno/blocks/new.js.erb
$('#<%= @block.before_element %>').before("<%=j render partial: "ryno/blocks/show", block: @block %>")

app/views/ryno/blocks/show.html.erb
<%= turbo_frame_tag "page_#{@page.id}_blockform" do %>
  <%= render partial: 'ryno/blocks/show' %>
  <%= render partial: 'ryno/blocks/new' %>
<% end %>

app/views/ryno/blocks/show.js.erb
if ($(".block_<%= @block.id %>").length>0) {
  $(".page_<%= @block.page_id %>_blocks").append("<%=j render partial: 'ryno/blocks/edit', block: @block %>")
} else {
  $(".block_<%= @block.id %>").replaceWith("<%=j render partial: 'ryno/blocks/edit', block: @block %>")
}

app/views/ryno/blocks/update.js.erb
$("#block_<%= @block.id %>").replaceWith("<%=j render partial: 'ryno/blocks/edit', locals: { block: @block } %>")

app/views/ryno/pages/_content.html.erb
<script>
  PageContent = {};
  PageContent.content = JSON.parse(<%= @page.content %>);
  //PageContent.content = [{type: "html", content: "<div class=''>blah</div>"}]
  // raw,paragraph,column,image
  PageContent.render_content = function () {
    for (var i=0;i<PageContent.content.length;i++) {
      var c = PageContent.content[i];
      if (c.type == 'raw') {
        var e = document.createElement("TEXTAREA");
        e.textContent = c.content;
        $(".content_area").append(e)
      } else if (c.type == '') {

      }
    }
  }
  PageContent.add_block = function () {
    // + paragraph or column or image or raw

  }

  PageContent.save = function () {
    JSON.stringify(PageContent.content);
  }
</script>

app/views/ryno/pages/_form.html.erb
<%= form_with(model: page, method: (page.new_record? ? :post : :patch), local: false) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this challenge from being saved:</h2>
      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <a href="#" onclick="$('.advanced').toggle();return false;">Advanced Options</a>
  </div>

  <div class="advanced" style="display:none;">
    <div class="form-group">
      <%= form.label :seo_title %>
      <%= form.text_field :seo_title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :url %>
      <%= form.text_field :url, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :redirect_to %>
      <%= form.text_field :redirect_to, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :css_classes %>
      <%= form.text_field :css_classes, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%#= form.submit %>
    <% if @page.new_record? %>
      <button type="submit" class="btn btn-primary" action="submit" name="save">Save</button>
    <% end %>
  </div>
<% end %>

<div class="page_<%= @page.id %>_blocks p-2 mt-4 mb-4 pageblocks">
  <%= render partial: 'ryno/blocks/index', page: @page %>
</div>

<script>
  var FormMagic = {}
  FormMagic.initialize = function () {
    if ($("input[name='page[seo_title]']").val() == $("input[name='page[title]']").val()) {
      $("input[name='page[seo_title]']").addClass('follows')
    }
    if ($("input[name='page[url]']").val() == FormMagic.title_to_url()) {
      $("input[name='page[url]']").addClass('follows')
    }
    var a = $("input[name='page[title]']");a.on("change",FormMagic.change_title);
    var b = $("input[name='page[seo_title]']");b.on("keypress",function() {b.removeClass('follows')});
    var c = $("input[name='page[url]']");c.on("keypress",function() {c.removeClass('follows')});
    var d = $("input[name='page[seo_title]']");d.on("change",function() {d.val()==''&&(d.val($("input[name='page[title]']").val()),$("input[name='page[url]']").addClass('follows'))})
    var e=$("input[name='page[url]']");e.on("change",function() {e.val()==''&&(e.val(FormMagic.title_to_url()),e.addClass('follows'))})
  }
  FormMagic.change_title = function () {
    if ($("input[name='page[seo_title]']").attr('class').indexOf('follows') >= 0) {
      $("input[name='page[seo_title]']").val($("input[name='page[title]']").val());
    }
    if ($("input[name='page[url]']").attr('class').indexOf('follows') >= 0) {
      $("input[name='page[url]']").val(FormMagic.title_to_url());
    }
  }
  FormMagic.title_to_url = function () {
    var url = $("input[name='page[title]']").val().toLowerCase();
    url = url.replace(/[^a-z0-9]/gi, '-');
    return url;
  };
  FormMagic.post_blocks = function () {
    FormMagic.post_form('blocks');
    FormMagic.post_form('pages');
  }
  <% unless @page.new_record? %>
  FormMagic.post_and_publish = function () {
    FormMagic.post_blocks();
    setTimeout(function() {$.get("<%= publish_page_path(@page) %>")},1000);
  }
  <% end %>
  FormMagic.post_form = function (name) {
    $("form").each(function (i) {
      var b = $(this);
      var url = b.attr('action')
      if (url.indexOf(name) < 0) {
        return
      }
      this.requestSubmit();
    });
  }
  FormMagic.eachx = function () {
    $("form").each(function (i) {
      var b = $(this);
      var url = b.attr('action')
      if (url.indexOf('blocks') < 0) {
        return
      }
      var data = $(this).serializeArray().reduce(function(obj, item) {
        obj[item.name] = item.value;
        return obj;
      }, {});
      $.ajax({
        url: url,
        method: 'post'
      })
    });
  };
  (function(){var r = setInterval(function(){"undefined"!=typeof $&&(clearInterval(r),FormMagic.initialize())},300);})();

</script>
<style>
  .block .block-opts>div, .addblockbuttons {
    opacity:0;
    transition:0.5s all;
  }
  .block:hover .block-opts>div, .pageblocks:hover .addblockbuttons {
    opacity: 0.1;
  }
  .block .block-opts:hover>div, .pageblocks .addblockbuttons:hover {
    opacity:1;
  }
  .block .block_types {
    display: none;
  }
  trix-toolbar .trix-button-group.trix-button-group--history-tools {
    display: none;
  }
  .col-3 .trix-button-group--file-tools, .col-3 .trix-button-group--block-tools, .col-3 .trix-button-group-spacer {
    display: none;
  }
  .xt-50 {
    margin-top: -50px;
  }
</style>

app/views/ryno/pages/_show.html.erb
<% @page = page if (@page.nil? && defined?(page)) %>
<% @no_edit_button = no_edit_button if (@no_edit_button.nil? && defined?(no_edit_button)) %>
<% @containment = "<div class='page container #{@page.css_classes}'>" %>
<% @end_containment = "</div>" %>
<% @contain = true %>
<% @contain = false if (@page.blocks.present? && @page.blocks.first.dont_contain) %>
<% if @contain %>
  <%=raw @containment %>
  <div class="pt-2 pb-2">
    <h1><%= @page.title %></h1>
  </div>
<% end %>
<% for @block in @page.blocks %>
  <% if @block.dont_contain %>
    <% if @contain %>
      <%=raw @end_containment %>
      <% @contain = false %>
    <% end %>
  <% else %>
    <% unless @contain %>
      <%=raw @containment %>
      <% @contain = true %>
    <% end %>
  <% end %>
  <%= render @block %>
<% end %>
<% if @contain %>
  <%=raw @end_containment %>
<% end %>
<% unless @no_edit_button %>
  <div class="p-2">
    <%= link_to "Edit Page", edit_page_path(@page), class: 'btn btn-primary' %>
    <%= link_to "Publish Page", publish_page_path(@page), class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/ryno/pages/edit.html.erb
<div class="breadcrumbs">
  <%= link_to "Pages", pages_path %> &raquo;
  <%= @page.title %>
</div>
<%= turbo_frame_tag @page do %>
  <h3>
    Editing Page
    <li class="d-inline-block mb-0 rem1" style="font-size:1rem;"><a href="/<%= @page.url %>" target="_blank"><i class="fas fa-external-link"></i></a></li>
  </h3>

  <div class="fixed-top p-2 bg-light text-right pr-4 page_options">
    <a href="#" onclick="FormMagic.post_blocks();return false;" class="btn btn-secondary">Save Draft</a>
    <a href="#" onclick="FormMagic.post_and_publish();return false;" class="btn btn-primary">Publish</a>
  </div>

  <div class="edit_page">
    <%= render 'form', page: @page %>
  </div>

  <div class="pt-4">
    <%= link_to 'Show', @page %> |
    <%= link_to 'Back', pages_path %>
  </div>

<% end %>
<style>
  .edit_page textarea {
    border: 1px solid #FFF;
  }
  .edit_page textarea:hover {
    border: 1px solid #CCC;
  }
</style>

app/views/ryno/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<% for @page in @pages %>
  <div class="row">
    <div class="col-4"><%= link_to @page.get_title, edit_page_path(@page) %></div>
    <div class="col-3"><%= link_to @page.url, @page.url %></div>
  </div>
<% end %>

<br>

<%= link_to 'New Page', new_page_path, class: 'button' %>

app/views/ryno/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/ryno/pages/show.html.erb
<%= render partial: "ryno/pages/show" %>

app/views/ryno/publishedpages/index.html.erb
<h1>Publishedpages#index</h1>

app/views/ryno/publishedpages/show.html.erb
<%=raw @publishedpage.content %>